/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 baked.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/baked.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="RootNode" position={[-0.812, 0, 1.105]}>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={materials['Material.002']} position={[0.044, 0.696, -0.077]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Empty" position={[-0.977, 0.536, -0.151]}>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[1.72, -0.536, -0.067]} />
        <group name="Cube004" position={[0.169, -0.21, 0.042]}>
          <mesh name="Cube004-Mesh" geometry={nodes['Cube004-Mesh'].geometry} material={materials.Wood} />
          <mesh name="Cube004-Mesh_1" geometry={nodes['Cube004-Mesh_1'].geometry} material={materials['Metal-2']} />
          <mesh name="Cube004-Mesh_2" geometry={nodes['Cube004-Mesh_2'].geometry} material={materials.Paper} />
        </group>
        <group name="Cube006" position={[0.426, -0.323, 0.332]}>
          <mesh name="Cube006-Mesh" geometry={nodes['Cube006-Mesh'].geometry} material={materials.Wood} />
          <mesh name="Cube006-Mesh_1" geometry={nodes['Cube006-Mesh_1'].geometry} material={materials.Blanket} />
        </group>
        <group name="Cylinder" position={[0.081, 0.008, 0.202]}>
          <mesh name="Cylinder-Mesh" geometry={nodes['Cylinder-Mesh'].geometry} material={materials.Black} />
          <mesh name="Cylinder-Mesh_1" geometry={nodes['Cylinder-Mesh_1'].geometry} material={materials.Wood} />
          <mesh name="Cylinder-Mesh_2" geometry={nodes['Cylinder-Mesh_2'].geometry} material={materials.Pencil} />
        </group>
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Lamp} position={[-0.158, 0.004, -0.23]} />
        <group name="Laptop_Cube010" position={[-0.171, 0.067, 0.142]}>
          <mesh name="Laptop_Cube010-Mesh" geometry={nodes['Laptop_Cube010-Mesh'].geometry} material={materials.Metal} />
          <mesh name="Laptop_Cube010-Mesh_1" geometry={nodes['Laptop_Cube010-Mesh_1'].geometry} material={materials.TVGlass} />
          <mesh name="Laptop_Cube010-Mesh_2" geometry={nodes['Laptop_Cube010-Mesh_2'].geometry} material={materials.Keyboard} />
        </group>
      </group>
      <mesh name="rubber_duck_toy" geometry={nodes.rubber_duck_toy.geometry} material={materials.rubber_duck_toy} position={[-0.954, 0, -1]} rotation={[-Math.PI, 0.913, -Math.PI]} />
      <mesh name="Plane-Mesh" geometry={nodes['Plane-Mesh'].geometry} material={materials.Wall} />
      <mesh name="Plane-Mesh_1" geometry={nodes['Plane-Mesh_1'].geometry} material={materials.Floor} />
    </group>
  )
}

useGLTF.preload('/baked.gltf')
