/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/XBot.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'

export default function XBot(props: any) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/XBot.glb')
  // const PrayingAnimation = useLoader(FBXLoader, '/Praying.fbx');
  const { animations: PrayingAnimation } = useFBX('/Praying.fbx');
  console.log(PrayingAnimation);
  PrayingAnimation[0].name = "Praying";
  const { actions } = useAnimations(PrayingAnimation, group);
  useEffect(() => {
    actions['Praying']?.reset().play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, Math.PI, Math.PI]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh geometry={nodes.Beta_Joints.geometry} material={materials.Beta_Joints_MAT1} skeleton={nodes.Beta_Joints.skeleton} />
        <skinnedMesh geometry={nodes.Beta_Surface.geometry} material={materials.Beta_HighLimbsGeoSG3} skeleton={nodes.Beta_Surface.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/XBot.glb')
